import 'dart:convert';
import 'dart:io';

import 'package:test/test.dart';
import 'package:shiori/domain/content_identity.dart';
import 'package:shiori/domain/models/models.dart';

void main() {
  // Independently calculated with .NET SHA256.HashData over these exact UTF-8
  // JSON inputs, not generated by the implementation under test.
  test('normalization v1 fixed UTF-8 SHA-256 vectors', () {
    final paragraph = ParagraphBlock(text: '中文，かな😀\r\n下一行', leadingIndent: 2);
    expect(
      ContentIdentity.canonicalInput('paragraph', paragraph.semanticFields),
      r'["shiori",1,"paragraph",["中文，かな😀\n下一行","start",2]]',
    );
    expect(
      paragraph.semanticDigest,
      '654324c90a6e8dc085520d1a2fdb3e2ee8afe3ad4eebcb22288e8f88ae1afff9',
    );
    expect(
      paragraph.blockKey,
      '1d63e155ae477cb88eaec3e56116840a40690cc90d8cb52d8ef46de156ed1b37',
    );
    expect(
      paragraph.withOccurrence(1).blockKey,
      'f44a94f32a1406ec5a846787d5c6ddd1dcfe229823f4b3d80b704f4bfd729518',
    );
  });

  test(
    'pure Dart example gives identical serialized content across processes',
    () async {
      final config = File('.dart_tool/package_config.json').absolute;
      final packages =
          (jsonDecode(config.readAsStringSync())
                  as Map<String, dynamic>)['packages']
              as List<dynamic>;
      final flutter = packages.cast<Map<String, dynamic>>().singleWhere(
        (p) => p['name'] == 'flutter',
      );
      final root = config.uri.resolve('${flutter['rootUri']}/');
      final executable = root
          .resolve(
            '../../bin/cache/dart-sdk/bin/${Platform.isWindows ? 'dart.exe' : 'dart'}',
          )
          .toFilePath();
      Future<ProcessResult> run() => Process.run(
        executable,
        ['--packages=${config.path}', 'tool/domain_example.dart'],
        stdoutEncoding: utf8,
        stderrEncoding: utf8,
      );
      final first = await run();
      final second = await run();
      expect(first.exitCode, 0, reason: '${first.stderr}');
      expect(second.exitCode, 0, reason: '${second.stderr}');
      expect(first.stdout, second.stdout);
      final output = jsonDecode(first.stdout as String) as Map<String, dynamic>;
      final serialized = output['content'] as Map<String, dynamic>;
      final chapter = ChapterContent.fromJson(serialized);
      expect(
        chapter.blocks[0].blockKey,
        '1d63e155ae477cb88eaec3e56116840a40690cc90d8cb52d8ef46de156ed1b37',
      );
      expect(
        chapter.blocks[1].blockKey,
        'f44a94f32a1406ec5a846787d5c6ddd1dcfe229823f4b3d80b704f4bfd729518',
      );
      expect(chapter.contentRevision, serialized['contentRevision']);
      expect(
        chapter.blocks[2].blockKey,
        'cf7a6c204cd4215640924d445fe36fa37c6bf44ad39a3e735d601800874d3205',
      );
      expect(
        chapter.contentRevision,
        'c65956754b6b82850b3642cfc1163c6420dedde8ba6acc4f87672f6fe96de4a0',
      );
      expect(
        output['catalogRevision'],
        '4e64e3efb54fffc2914b88169642e1919240905bde587a80abeedbdbc6ac8683',
      );
      expect(output['catalogRevision'], matches(RegExp(r'^[a-f0-9]{64}$')));
    },
  );
}
