"""Generate WHATWG indexes from explicit input files, without network access.
Usage: python3 tool/encoding/generate.py index-gb18030.txt index-gb18030-ranges.txt
"""
from pathlib import Path
import base64
import hashlib
import struct
import sys
out = ['// Generated by tool/encoding/generate.py. Do not edit.',
       '// Copyright WHATWG (Apple, Google, Mozilla, Microsoft).',
       '// BSD-3-Clause; see tool/encoding/LICENSE.',
       "import 'dart:convert';", "import 'dart:typed_data';", '']
for filename, name, dense in zip(sys.argv[1:], ['gb18030Index', 'gb18030Ranges'], [True, False]):
    data = Path(filename).read_bytes()
    out += ['// https://encoding.spec.whatwg.org/index-gb18030' + ('' if dense else '-ranges') + '.txt',
            '// SHA-256: ' + hashlib.sha256(data).hexdigest()]
    rows = [line.split()[:2] for line in data.decode().splitlines() if line.strip() and not line.startswith('#')]
    pairs = [(int(a), int(b, 16)) for a, b in rows]
    if dense:
        assert len(pairs) == 23940 and all(a == i and b <= 65535 for i, (a,b) in enumerate(pairs))
        encoded = base64.b64encode(b''.join(struct.pack('<H', b) for a,b in pairs)).decode()
        out += ['final _index = ByteData.sublistView(base64Decode(_encodedIndex));',
                'int gb18030At(int pointer) => _index.getUint16(pointer * 2, Endian.little);',
                'const _encodedIndex =']
        out += ["    '" + encoded[i:i+80] + "'" + (';' if i+80 >= len(encoded) else '') for i in range(0,len(encoded),80)]
    else:
        out += ['const gb18030Ranges = <int>[']
        out += ['  '+str(a)+', '+str(b)+',' for a,b in pairs]
        out += ['];']
Path('lib/data/local/txt/gb18030_tables.dart').write_text('\n'.join(out)+'\n')
