import 'dart:collection';
import 'dart:convert';
import 'dart:math';

import 'package:crypto/crypto.dart';

import '../domain/contracts/contracts.dart';
import '../domain/models/models.dart';

enum DiagnosticLevel { info, warning, error }

/// No free-form message/exception/map API: secrets cannot enter these events.
final class DiagnosticEvent {
  DiagnosticEvent._(this.fields);
  final Map<String, Object> fields;
  @override
  String toString() => jsonEncode(fields);
}

class AppLogger {
  AppLogger({
    this.release = const bool.fromEnvironment('dart.vm.product'),
    this.capacity = 200,
    DateTime Function()? now,
  }) : now = now ?? DateTime.now {
    if (capacity < 1 || capacity > 200) {
      throw ArgumentError('Invalid log capacity');
    }
  }
  final bool release;
  final int capacity;
  final DateTime Function() now;
  final _events = Queue<DiagnosticEvent>();
  List<DiagnosticEvent> get events => List.unmodifiable(_events);
  final _random = Random.secure();
  String newRequestId() => List.generate(
    16,
    (_) => _random.nextInt(256).toRadixString(16).padLeft(2, '0'),
  ).join();

  void network({
    required SourceId source,
    required Operation operation,
    required String requestId,
    required Duration duration,
    int attempt = 1,
    int? status,
    int bytes = 0,
    AppFailure? failure,
  }) {
    // IDs are locally generated by this layer, never forwarded response IDs.
    if (!RegExp(r'^[a-f0-9]{32}$').hasMatch(requestId)) {
      throw ArgumentError('Invalid diagnostic ID');
    }
    if (failure?.isCancellation ?? false) return;
    final level = failure == null
        ? DiagnosticLevel.info
        : DiagnosticLevel.warning;
    if (release && level == DiagnosticLevel.info) return;
    _events.add(
      DiagnosticEvent._(
        Map.unmodifiable({
          'timestamp': now().toUtc().toIso8601String(),
          'level': level.name,
          'requestId': requestId,
          // SourceId is opaque and not guaranteed to be a safe printable label.
          'sourceId': sha256.convert(utf8.encode(source.value)).toString(),
          'operation': operation.name,
          'durationMs': max(0, duration.inMilliseconds),
          'attempt': attempt,
          'bytes': bytes,
          'httpStatus': ?status,
          if (failure != null) 'failureKind': failure.kind.name,
        }),
      ),
    );
    while (_events.length > capacity) {
      _events.removeFirst();
    }
  }
}
